# Site settings
title: IS2RI - Information Security and Intelligence Sharing Research Institute
email: 
description: > # this means to ignore newlines until "baseurl:"
  IS2RI - Information Security Intelligence Sharing Research Institute
baseurl: "/is2ri" # the subpath of your site, e.g. /blog/
url: "http://www.foo.be/" # the base hostname & protocol for your site
#twitter_username: username
#github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
